name: Docker Image CI

on:
  push:
    branches: [ "docker*","github*" ]
  pull_request:
    branches: [ "docker*","github*" ]

jobs:

  build_docker_image:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ubuntu_headless:$(date +%s)
      
    - name: Upload image
      uses: ishworkh/docker-image-artifact-upload@v1
      with:
        image: "ubuntu_headless:latest"
