name: Docker Image CI

on:
  push:
    branches: [ "docker*" ]
  pull_request:
    branches: [ "docker*" ]

jobs:

  build_docker_image:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Create Directory
      run: mkdir -p /var/lib/docker
    
    - name: Cache Docker
      uses: ScribeMD/docker-cache@0.1.4
      with:
        key: ${{ runner.os }}-build-cache-docker-layer-${{ hashFiles('**/image/overlay2/repositories.json') }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

# Comment
