name: Docker Image CI

on:
  push:
    branches: [ "docker*","github*" ]
  pull_request:
    branches: [ "docker*","github*" ]

jobs:

  build_docker_image:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ubuntu_headless:$(date +%s) --tag ubuntu_headless:latest
      
    - name: Upload image latest
      uses: ishworkh/docker-image-artifact-upload@v1
      with:
        image: "ubuntu_headless:latest"

  upload_to_docker_hub:
    needs: build_docker_image

    runs-on: ubuntu-latest

    steps: 
    
    - name: Download the Latest Image
      uses: ishworkh/docker-image-artifact-download@v1
      with:
        image: "ubuntu_headless:latest"
    
    - name: Show Images
      run: docker images

    # - name: Login to Docker Hub
    #   run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }} docker.io

    # - name: Push the image to Docker Hub
    #   run: docker push ubuntu_headless:latest
    