name: Docker Image CI

on:
  push:
    branches: [ "docker*","github*" ]
  pull_request:
    branches: [ "docker*","github*" ]
  workflow_dispatch:


env:
  IMAGENAME: ubuntu_headless
  IMAGETAG: latest
  TEST_TAG: user/myapp:test

jobs:

  build_and_upload_to_docker_hub:

    runs-on: ubuntu-latest

    steps: 
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and export to Docker
      uses: docker/build-push-action@v3
      with:
        load: true
        tags: ${{ env.TEST_TAG }}
    
    - name: Test if the Image is even running
      run: |
        docker run --rm ${{ env.TEST_TAG }}

    - name: Test if it can run a Bash Shell
      run: |
         docker run ${{ env.TEST_TAG }} bash

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.DOCKER_USER }}/${{ env.IMAGENAME }}:${{ env.IMAGETAG }}

