name: Sync Main Branches

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  # This workflow syncs master to docker branch
  merge_docker:
    name: Sync Docker Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> docker
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: master
          target_branch: docker
          github_token: ${{ github.token }}
  merge_github:
    name: Sync GitHub Branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> github
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: master
          target_branch: github
          github_token: ${{ github.token }}
